orgs:
  kingdom-tower:
    admins:
    - cpanato
    - jespino
    - mgdelacroix
    billing_email: ctadeu@gmail.com
    company: ""
    default_repository_permission: read
    description: ""
    email: ""
    has_organization_projects: true
    has_repository_projects: true
    location: ""
    members:
    - cpanatoBOT
    members_can_create_repositories: true
    name: kingdom-tower
    repos:
      kingdom:
        has_projects: false
        has_wiki: false
      playground:
        default_branch: main
        has_projects: false
        has_wiki: false
      testing:
        default_branch: main
        has_projects: true
    teams:
      A Team with space:
        description: super cool team
        maintainers:
        - cpanato
        privacy: closed
        repos:
          playground: triage
      My team 2:
        description: super cool team
        maintainers:
        - cpanato
        privacy: closed
        repos:
          playground: read
      mytestingteam:
        description: just to test
        maintainers:
        - cpanato
        members:
        - cpanatoBOT
        privacy: closed
      team-b:
        description: super cool team
        maintainers:
        - cpanato
        privacy: closed
        repos:
          playground: write
      team-c:
        description: another super cool team
        privacy: closed
