name: verify

on:
  push:
  pull_request:

permissions: read-all

env:
  GO_VERSION: 1.17.x

jobs:
  license-check:
    name: license boilerplate check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.2.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Peribolos
        uses: docker://docker.io/ctadeu/peribolos:test --help

