name: periobolos

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check-config:
    if: github.event_name == 'pull_request'
    name: check-config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0
      - name: set token
        run: echo ${{ secrets.GITHUB_TOKEN }} > token
      - name: Peribolos
        uses: docker://docker.io/ctadeu/peribolos:test
        with:
          config-path: ./config.yaml
          github-token-path: ./token
          fix-org: true
          fix-org-members: true
          min-admins: 2

  apply-config:
    if: github.ref == 'refs/heads/main'
    name: apply-config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0
      - name: set token
        run: echo ${{ secrets.GITHUB_TOKEN }} > token
      - name: Peribolos
        uses: docker://docker.io/ctadeu/peribolos:test
        with:
          config-path: ./config.yaml
          github-token-path: ./token
          confirm: true
          fix-org: true
          fix-org-members: true
          min-admins: 2
