name: verify

on:
  push:
  pull_request:

permissions: read-all

env:
  GO_VERSION: 1.17.x

jobs:
  license-check:
    name: license boilerplate check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0
      - name: set token
        run: echo ${{ secrets.GITHUB_TOKEN }} > token
      - name: Peribolos
        uses: docker://docker.io/ctadeu/peribolos:test
        with:
          config-path: ./config.yaml
          github-token-path: ./token
