name: periobolos-dump

on:
  workflow_dispatch:

permissions: read-all

jobs:
  dump-config:
    name: dump-config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0
      - name: set token
        run: echo ${{ secrets.PAT_TOKEN }} > token
      - name: Peribolos
        # uses: docker://ghcr.io/relengfam/peribolos:latest
        uses: docker://ctadeu/peribolos:latest
        with:
          github-token-path: ./token
          dump: kingdom-tower
