name: periobolos-dump

on:
  workflow_dispatch:

jobs:
  dump-config:
    name: dump-config
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v2.4.0
      - name: set token
        run: echo ${{ secrets.GITHUB_TOKEN }} > token
      - name: Peribolos
        uses: docker://docker.io/ctadeu/peribolos:test
        with:
          github-token-path: ./token
          dump: "${GITHUB_REPOSITORY_OWNER}"
