name: Review

on:
  workflow_run:
    workflows: ["periobolos-check"]
    types:
      - completed

jobs:
  review:
    runs-on: ubuntu-latest

    # permissions:
    #   pull-requests: write
    #   contents: read

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      # - run: |
      #     set -euo pipefail
      #     ./.github/scripts/review-pull-request.sh ${{ github.repository }}
      #   shell: bash
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo "${{ github.context.pull_requests.number }}"
      - run: echo "${{ github.context.workflow_run.actor.login }}"

      - uses: actions/github-script@v4
        with:
          script: |
            const result = await github.pulls.createReview({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            event: "APPROVE"
            })
            console.log(result.status)
